export const dummyData = [
  {
    type: "autocomplete",
    required: false,
    label: "Brand",
    className: "brand",
    name: "brand",
    access: false,
    requireValidOption: false,
    QueryRule: "ayurveda_get_brand_list",
    values: [
      {
        label: "",
        value: "",
        selected: true,
      },
    ],
  },
  {
    type: "text",
    required: true,
    label: "Title",
    className: "form-control",
    name: "title",
    access: false,
    subtype: "text",
  },
  {
    type: "select",
    required: true,
    label: "Category",
    className: "category_name",
    name: "category",
    access: false,
    multiple: false,
    values: [
      {
        label: "Health & Wellness",
        value: "health_wellness",
        selected: true,
      },
      {
        label: "Personal Care",
        value: "personal_care",
        selected: false,
      },
      {
        label: "Herbal Juices & Drinks",
        value: "herbal_juices_drinks",
        selected: false,
      },
      {
        label: "Classical Ayurvedic Medicines",
        value: "classical_ayurvedic_medicines",
        selected: false,
      },
      {
        label: "Nutritional Supplements",
        value: "nutritional_supplements",
        selected: false,
      },
    ],
  },
  {
    type: "select",
    required: false,
    label: "Sub Category",
    className: "sub_category",
    name: "sub_category",
    access: false,
    multiple: false,
    values: [
      {
        label: "",
        value: "",
        selected: true,
      },
    ],
  },
  {
    type: "file",
    required: false,
    label: "Image",
    className: "form-control",
    name: "image",
    access: false,
    multiple: false,
  },
  {
    type: "radio-group",
    required: false,
    label: "Prescription",
    inline: false,
    name: "prescription_required",
    access: false,
    other: false,
    values: [
      {
        label: "Yes",
        value: "yes",
      },
      {
        label: "No",
        value: "no",
      },
    ],
  },
  {
    type: "text",
    required: false,
    label: "HSN No",
    className: "hsn_no",
    name: "hsn_no",
    access: false,
    subtype: "text",
  },
   {
    type: "select",
    required: false,
    label: "Select GST",
    className: "form-control",
    name: "gst_percentage",
    access: false,
    multiple: false,
    values: [
      {
        label: "5%",
        value: "5%",
        selected: true,
      },
      {
        label: "12%",
        value: "12%",
      },
      {
        label: "18%",
        value: "18%",
      },
    ],
  },
    {
    type: "textarea",
    required: false,
    label: "Description",
    className: "form-control",
    name: "description",
    access: false,
    subtype: "textarea",
  },
  {
    type: "checkbox-group",
    required: false,
    label: "Inventory Selling",
    toggle: false,
    inline: false,
    name: "is_inventory",
    access: false,
    DataType: "integer(11) default(0)",
    values: [
      {
        label: "Inventory Selling",
        value: "1",
        selected: true,
      },
    ],
  },
  {
    type: "number",
    required: false,
    label: "Employee Percentage",
    className: "form-control",
    name: "employee_percentage",
    access: false,
    subtype: "number",
  },
];